import page from 'page';
import { ctxDecorator } from './layout.js';
import { aboutPage } from './views/about.js';
import { accessoriesPage } from './views/accessories.js';
import { bikesPage } from './views/bikes.js';
import { blogPage } from './views/blog.js';
import { createPage } from './views/create.js';
import { homePage } from './views/home.js';
import { loginPage } from './views/login.js';
import { registerPage } from './views/register.js';
import { logoutAction } from './views/logout.js';
import { articleDetailsPage } from './views/detailsArticle.js';
import { bikeDetailsPage } from './views/detailsBike.js';
import { addPost } from './views/addPost.js';
import { showNav } from './middlewares/showNav.js';
import { showFooter } from './middlewares/showFooter.js';
import { userSession } from './middlewares/session.js';
import { getUserData } from './utils/userData.js';
import { hasUser, isNotGuest } from './middlewares/guards.js';
import { showPageLoading } from './middlewares/loadingTemplate.js';
import { helmetsPage } from './views/helmets.js';
import { notFoundPage } from './views/notFound.js';

import '../styles/main.scss';
import { antiClickSpam } from './middlewares/antiClickSpam.js';
import { cartPage } from './views/cart.js';

page(userSession(getUserData));
page(antiClickSpam);
page(ctxDecorator);
page(showNav);
page(showFooter);
page(showPageLoading);
page('/', homePage);
page('/index.html', '/');
page('/blog', blogPage);
page('/bikes', bikesPage);
page('/accessories', accessoriesPage);
page('/accessories/helmets', helmetsPage);
page('/about', aboutPage);
page('/article', articleDetailsPage);
page('/article/:id', articleDetailsPage);
page('/bike-details/:id', bikeDetailsPage);
page('/create', hasUser(), createPage);
page('/add-post', hasUser(), addPost);
page('/login', isNotGuest(), loginPage);
page('/register', isNotGuest(), registerPage);
page('/cart', hasUser(), cartPage);
page('/logout', notFoundPage);
page('*', notFoundPage);

page.start();